// Generated by https://quicktype.io

export interface TForecast {
  latitude: number;
  longitude: number;
  generationtime_ms: number;
  utc_offset_seconds: number;
  timezone: string;
  timezone_abbreviation: string;
  elevation: number;
  daily_units: DailyUnits;
  daily: Daily;
  current_weather: CurrentWeather;
}

export interface Daily {
  time: string[];
  apparent_temperature_max: number[];
  apparent_temperature_min: number[];
  precipitation_probability_mean: number[];
  weathercode: number[];
  windspeed_10m_max: number[];
}

export interface DailyUnits {
  time: string;
  apparent_temperature_max: string;
  apparent_temperature_min: string;
  precipitation_probability_mean: string;
  weathercode: string;
  windspeed_10m_max: string;
}

export interface WeatherModal {
  dayNumber: string;
  averageTemp: string;
  chanceToRain: string;
  minTemp: number;
  maxTemp: number;
  wind: string;
  weathercode: number;
}

export interface CurrentWeather {
  time: string;
  temperature: number;
  windspeed: number;
  winddirection: number;
  is_day: number;
  weathercode: number;
}

export interface WeatherData {
  dayNumber: string;
  averageTemp: string;
  chanceToRain: string;
  minTemp: number;
  maxTemp: number;
  wind: string;
  weathercode: number;
  humidity: number;
}

export interface TodayWeather {
  title: string;
  value: string | number;
  icon: string;
}
